package com.project.demo.dto.chat;

import com.project.demo.Entity.ChatEvent;
import com.project.demo.Entity.ChatSession;
import com.project.demo.Entity.enums.MessageRole;


import java.time.Instant;
import java.util.List;

public record ChatResponse(
        Long id,
        String content,
        MessageRole role, // Message role present in enum ex assistant means generated by llm , user means asked by me
        List<ChatEventResponse> events,
        Integer tokensUsed,
        Instant createdAt

)
{ }
